language: node_js
branches:
  only:
  - master
before_script: npm install -g grunt-cli
script: grunt build-prod
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: leunggriggsdronez
  acl: public_read
  region: Oregon
  detect_encoding: true
  skip_cleanup: true
  local-dir: dist
  on:
    repo: gleung93/drones1.0
